apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: team2-app
  name: team2-app
  namespace: apps2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: 
          limits:
            cpu: 0.5 